updating READMEs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,15 +18,15 @@ jobs:
         run: |
           pip3 install jsonschema
           pip3 install requests
-      - name: Check validity of traces
+      - name: Check validity of instances
         run: |
-          find . -type f -name "*.json" > traces.txt && err=0
+          find . -type f -name "*.json" > instances.txt && err=0
           git clone https://github.com/wfcommons/workflow-schema
           err_report() {
-            echo "Error on trace file $1"
+            echo "Error on instance file $1"
           }
-          trap 'err_report ${trace_file}' ERR;
-          for trace_file in `cat traces.txt`; do
-            python3 ./workflow-schema/wfcommons-validator.py -d ${trace_file};
+          trap 'err_report ${instance_file}' ERR;
+          for instance_file in `cat instances.txt`; do
+            python3 ./workflow-schema/wfcommons-validator.py -d ${instance_file};
             echo "";
           done
